### ISSUE TITLE
Allow custom index.html

### ISSUE THREAD

**Issue by cdekok** [electron-userland/electron-webpack#104]
I have seen this come up many time before but the other issues where closed, i would still like to make the case for custom html for example now I want to use vue router and if you look at the example:
https://router.vuejs.org/en/essentials/getting-started.html
It needs some custom html in there and it's just easier to write this in html then doing it in some template and replace the current html with js.

**Comment by Gum-Joe** [comment]
@cdekok This issue is very long running, although @loopmode has discovered you can build a custom HTML via JS yourself (below is from Slack thread):

> loopmode 
Btw, I just tried out `document.documentElement.innerHTML = require('./index.html');` and it works. I tried the `electron-webpack-quick-start`, and if the html file provides a `div id="app"></div>`, everything is fine. (edited)

> loopmode
(first line in `renderer/index.js`)

> loopmode 
I still think whatever you want to achieve in that html file, you can do it via JS just as well (edited)

> loopmode
`document.body`, `document.head`, `innerHMTL`, `createElement`, `appendChild` - it's all there to add meta tags, css and whatnot

**Comment by cdekok** [comment]
Yes sure you can do it and I did but imho it's a bit uglier then if it is configurable.
Most people who want to build something would need to overwrite it anyway.

**Comment by loopmode** [comment]
The thing is: HTML is just a markup language, not much different from XML. What we actually work with is not HTML, it's the DOM. 
HTML may be used to initialize the DOM at startup, but that's it. 
HTML may be used to represent the DOM at a given later time, at least partially, but that's it.

The DOM is everything in our case, and javascript gives you full control over it. Full power. 
If we want to make real desktop applications, we need to let go of HTML's restrictions and start thinking like real programmers.

I've tried a couple of things with the custom html, but seriously, it's not worth it, not with the current state of `electron-webpack`.
Of course @develar could make `electron-webpack` understand custom html templates. But that would be a hell lot of work, and it would be wasted time because you can do _everything_ and _anything_ already, with javascript.

I was going into details for quite a while here, but I decided not to post it. Deleted it, now here's the summary:

If you wanna use `electron-webpack`, forget about HTML and embrace Javascript. You'll be powerful and efficient.
Otherwise, if you want to work basically with HTML, and use JS and CSS "on top" to make the HTML look or behave in a special way, just don't use `electron-webpack`. You can use `electron` itself and/or any other available boilerplate.

Btw, I'm not a maintainer, merely a user.

**Comment by loopmode** [comment]
Also, I apologize for my slightly harsh undertone. I'm just a bit frustrated myself that this isn't easier :)

**Comment by Gum-Joe** [comment]
@loopmode Well said, It really should be easier - so we can either give users the option (choice is better than no choice), but that appears to require a lot of work to do (and causes issues) or we could put a line in the docs to explain why and how to use JS to do it instead (which as you pointed out is more powerful, so in reality this is the better option, provided the user understands WHY this has been done)

**Comment by loopmode** [comment]
@develar Is there a particular reason for why the index file is generated and "virtual" in https://github.com/electron-userland/electron-webpack/blob/8b0865ad5250cc46ca4d277f5c9fbc7f27accfbd/packages/electron-webpack/src/targets/RendererTarget.ts#L177-L219 ?

The way I see it.. it should be possible to do it the "regular" webpack way. Seems electron-vue actually supports something like that? (https://github.com/SimulatedGREG/electron-vue/blob/master/template/src/index.ejs)

Because.. it's one thing if there is a good reason why the html is hard-coded, but if it's just a matter of work that needs to be done, I'd tackle that.

**Comment by loopmode** [comment]
Alternatively, `generateIndexFile` could look for an optional user-provided function of same name, and if found, invoke it passing the very same arguments. The user would be responsible for returning properly.

**Comment by loeck** [comment]
You can do that easily, see this line https://github.com/electron-userland/electron-webpack/blob/master/packages/electron-webpack/src/targets/RendererTarget.ts#L117

In my project we create a simple template file in root project `src/index.ejs`, with this content:

```
<!DOCTYPE html>
<html>
  <head>
    <title><%= process.env.npm_package_productName %></title>
    <meta charset="utf-8">
    <script>
      <% if (htmlWebpackPlugin.options.nodeModules) { %>
        require('module').globalPaths.push(
          '<%= htmlWebpackPlugin.options.nodeModules %>'.replace(/\\/g, '\\\\'),
        )
      <% } %>
      require('source-map-support/source-map-support.js').install()
    </script>
  </head>
  <body>
    <div id="app"></div>
  </body>
</html>
```

Annnnd, it's working.

**Comment by loopmode** [comment]
Well, yay everybody! What's all the hazzle about?
Maybe we just need proper and explicit documentation..

**Comment by Gum-Joe** [comment]
@loopmode @loeck Good point - I think I read this somewhere, but the problem is the location is not idea I. E. Some people prefer using `src/html`

**Comment by Gum-Joe** [comment]
I guess though if that is possible, then just adding a field for a .ejs file should also work, provided such boilerplate code is provided in docs.

**Comment by loopmode** [comment]
@loeck @develar 
When I try latest `electron-webpack-quick-start` and add a `src/index.ejs` with that exact content, I get errors about the `source-map-support` module:

```
module.js:485 Uncaught Error: Cannot find module 'source-map-support'
    at Module._resolveFilename (module.js:485)
    at Function.Module._resolveFilename (D:\Projects\electron\electron-webpack-quick-start\node_modules\electron\dist\resources\electron.asa…:35)
    at Function.Module._load (module.js:437)
    at Module.require (module.js:513)
    at require (internal/module.js:11)
    at (index):12
```
I tried `require('source-map-support').install()` as well, same effect. In fact, I can't require anything from the template, e.g `console.log(require('bluebird'))` throws the same error.

@Gum-Joe 
You can simply include/redirect via ejs import. 
Besides the error I just described (which I get in both the default case and when I do this import trick) it just works!

```
// src/index.ejs
<% include html/index %>
```

```
// src/html/index.ejs
<!-- the template as posted by loeck -->
```

**Comment by loeck** [comment]
@loopmode maybe just add `source-map-support` in your package.json ?

**Comment by loopmode** [comment]
Nah, it's there. That's also why I tried other definitely existing packages like `bluebird`.
The file is there, but the require just fails

**Comment by loeck** [comment]
Well, maybe just look the project, if you need an example:

package.json: https://github.com/LedgerHQ/ledger-wallet-desktop/blob/master/package.json#L95
index.ejs: https://github.com/LedgerHQ/ledger-wallet-desktop/blob/master/src/index.ejs

**Comment by loopmode** [comment]
Interesting, it's the same basic dependencies - I just used https://github.com/electron-userland/electron-webpack-quick-start/blob/master/package.json

Will try with specific version numbers (without `^`)

**Comment by loopmode** [comment]
Alright, created https://github.com/loopmode/electron-webpack-quick-start-error-require-in-ejs
It's really _just_ the quick start plus index.ejs

**Comment by loeck** [comment]
@loopmode 
![image](https://user-images.githubusercontent.com/582703/37141185-8a11d398-22b4-11e8-91b0-ce8d3873fbca.png)
Well, it's working on my side ^^'
```
▶ node --version
v9.7.1
▶ yarn --version
1.5.1
```

**Comment by loopmode** [comment]
crazy stuff!
I won't be able to check with different versions of node/yarn _just now_, but I'll try asap.
Currently:
```
$ node --version
v8.9.4
$ yarn --version
1.3.2

```

**Comment by cdekok** [comment]
Ok so I will close this issue :) seems that it already is possible with the ejs file it just needs documentation.

**Comment by Germain-Italic** [comment]
For people lost like me with ejs: https://github.com/electron-userland/electron-webpack/issues/197#issue-357469153

**Comment by ayeressian** [comment]
This solved my issues
**In template**
```html
<head>
<% if (htmlWebpackPlugin.options.nodeModules) { %>
    <!-- Add `node_modules/` to global paths so `require` works properly in development -->
    <script>
      require('module').globalPaths.push('<%= htmlWebpackPlugin.options.nodeModules.replace(/\\/g, '\\\\') %>');
      require('source-map-support/source-map-support.js').install();
    </script>
  <% } %>
</head>
```

**In JS**
```javascript
const HtmlWebpackPlugin = require('html-webpack-plugin');
const path = require('path');

module.exports = {
  plugins: [
    new HtmlWebpackPlugin({
      template: '!!ejs-loader!src/renderer/index.ejs',
      nodeModules: process.env.NODE_ENV !== 'production'
        ? path.resolve(__dirname, './node_modules')
        : false
    })
  ]
};
```

You should have ejs-loader installed and the js file should be webpack renderer config addition file in my case webpack.renderer.additions.js

**Comment by trusktr** [comment]
@loeck How do we open a second window using a second ejs file?

**Comment by loopmode** [comment]
Not a direct answer, but if possible, I would use the same entry - including the ejs file - and open it with a URL param of some kind, e.g. `?entry=other-app` or `/#other-app`, then programmatically detect that and import different files in JavaScript.
