### ISSUE TITLE
html-loader is un-escaping nodeModulesPath from generateIndexFile

### ISSUE THREAD

**Issue by BobBuehler** [electron-userland/electron-webpack#121]
This is the cause for Issue #120. I've tested two solutions locally but I'm not sure which is appropriate.

1. Don't use html-loader. This is achieved by removing the extension from `filePath` and by returning `filePath` rather than the `"!!html-loader"` string.
2. Escape it twice. Either `.replace(/\\/g, "\\\\\\\\")` or `.replace(/\\/g, "\\\\").replace(/\\/g, "\\\\")`.

Option three is to figure out why html-loader is un-escaping this text and stop it, but I did not succeed there.

I'm more a fan of option one, but I don't know what benefits we're getting from html-loader. I also haven't figured out how to run the test suite on my Windows machine so I'm not sure what else this might break.

**Comment by iOiurson** [comment]
Hi there !
Is there any development on this issue ?

I'm having the exact same pb as described in #120 when trying to build a distribution, and i haven't been able to solve it yet...

**Comment by iOiurson** [comment]
With a little digging, i appeared that in my case, the `source-map-support` was installed as `devDependency`, when it should have been as `dependency`.

**Comment by loopmode** [comment]
So...that solves it?? :o

@BobBuehler it's been a year and I apologize for missing response and support on this..but can you confirm whether this resolves your original issue?

**Comment by BobBuehler** [comment]
The quick-start works for me out of the box now. It seems to have switched to forward slashes from backslashes, so the escaping isn't an issue.

**Comment by loopmode** [comment]
Cool, let's close then!

**Comment by ZuBB** [comment]
Hi everyone!

Sorry for bumping so old thread.

@iOiurson do you recall what was the issue with "source-map-support" package?

I am in process of setting up "electron-userland" for my project and am wonder why in [installation doc](https://webpack.electron.build/development#installation) it stated as development dependency, however "source-map-support" is a regular dependency

@loopmode any insight on that? just newbie question: if "source-map-support" is really required maybe it should be moved as regular dependency for this project?

ps: it turned out you already have that. maybe docs need to be updated?
