### ISSUE TITLE
how to add react 

### ISSUE THREAD

**Issue by vivopcz** [electron-userland/electron-webpack#124]
i have add react , but has same problem.

https://github.com/electron-userland/electron-webpack-quick-start/issues/30

is there an docs to add react ?

**Comment by loopmode** [comment]
There is, but it's really not much: https://webpack.electron.build/add-ons#react-jsx

The source-map-support issue is really weird.. I hope somebody finds time to properly deal with it.

However, as I just mentioned in https://github.com/electron-userland/electron-webpack/issues/123, have a look at https://github.com/loopmode/electron-webpack-quick-start

A couple days ago, I cloned and installed it again, and at runtime I had the same error.
Just minutes ago I again cloned, installed and started it - and it worked.
Please try yourself and see if it works for you.

Since the last time..I didn't change any code. I did however upgrade my local node.js to latest version. I don't think it has to do with the node version, but I implicitly cleared all npm and yarn caches by doing it.

**Comment by vivopcz** [comment]
i reinstall  the node module , and the problem fix
