### ISSUE TITLE
custom renderer html 

### ISSUE THREAD

**Issue by farfromrefug** [electron-userland/electron-webpack#133]
Hi,
some of my renderer windows html files are custom (custom stylesheet linking like with xterm).

Is there a way for electron-webpack to use my html files?

**Comment by fabiospampinato** [comment]
@develar This is pretty important for performance. I'd like to show the window as soon as possible and have it render some kind of placeholder HTML.

I've tried mutating the DOM via `webContents.executeJavaScript` but that executes after all the bundled code so it doesn't make sense. I also thought about patching the `index.html` file that gets created on production builds, but that's pretty hacky, and it won't work on development builds.

I'd like to submit a PR for adding support to this, any thought on how I should implement this? I was thinking maybe there could be a `electronWebpack.renderer.initialHTML` option in `package.json` that accepts a path to an HTML file, which will be then used instead of the default one.

**Comment by loopmode** [comment]
FIxed with https://github.com/electron-userland/electron-webpack/pull/261
