### ISSUE TITLE
Common codes are duplicated in the main entry and renderer entry.

### ISSUE THREAD

**Issue by momocow** [electron-userland/electron-webpack#187]
Assume my project is structured as below,
```
└─ src
   ├─ common
   │    └─ lib.js
   ├─ main
   │    └─ main.js
   └─ renderer
        └─ renderer.js
```
Both `main.js` and `renderer.js` share the functions from `lib.js`.

However, after compilation with default configuration, the output seems to be like this.
```
└─ dist
   ├─ main
   │    └─ main.js ~ lib.js
   └─ renderer
        ├─ index.html
        └─ renderer.js ~ lib.js
```
The common codes, says `lib.js`, which was code-split by developers to avoid duplication is duplicated again. Actually, those codes that can be split are usually less context awareness or less side effects, no matter which process it is.

I think common codes should stay in a shared bundle instead of being duplicated. That is,
```
└─ dist
   ├─ main
   │    └─ main.js
   ├─ renderer
   │    ├─ index.html
   │    └─ renderer.js
   └ lib.bundle.js
```

However, I have not been digging into Webpack optimization. 🔰 
Currently, I have no idea how this can be achieved, if anyone can help, I will be much appreciate. 🙏

**Comment by JM-Mendez** [comment]
I don't think this is possible, since the main and renderer processes are completely separate os processes. See the moderator comment at [post #2](https://discuss.atom.io/t/electron-project-configuration-multiple-questions/38796/2) and [post #4](https://discuss.atom.io/t/electron-project-configuration-multiple-questions/38796/4). Also, each browserwindow is a separate processes.

Unless I'm mistaken, I take this to mean that webpack traverses the require graph independently for each. So there's no way to tell if code is being duplicated between them.

**Comment by momocow** [comment]
Can we just pack `common/` into a cjs lib bundle for `main/` and `renderer/` to require respectively. For `main/` and `renderer/`, `common/` is treated as an external dependency.

To pack `common/`, it is no matter the target is `electron-main` or `electron-renderer` since the codes you may put in `common/` must be able to run on both processes.

No webpack traverse is needed, since `common/` is split by **the programmer manually** from those process specific codes.

**Comment by JM-Mendez** [comment]
I'm not a webpack expert, but how are you splitting the code manually while bundling with webpack? I haven't come across this before, so maybe I'm missing something.

My understanding of how webpack works, is that it has to traverse the require graph to build a dependency tree. Even if you split your code manually. 

So from each entry point webpack will follow each require and make a bundle. I believe it also compares with the other entry points to avoid duplication.

But since the main and renderer process are separated, there are 2 webpack configs: 1 main, 1 renderer. And that's why webpack will bundle them separately. Because each process is bundle how it's read, through separate configs with their own entry points.

So extracting the code into a different directory only serves as a visual separation between the main and renderer codebase. You should think of an electron app as being 2 apps in 1 - a server (main process), and the frontend app (renderer). And those two don't share requires either.

#### Possible solution
One thing you could do is split out that code and publish it as a module. You can then declare it as an external dependency, which is how all the node modules are packed anyways (they aren't bundled into the main or renderer code). This way the main and renderer process will require it from the node_modules folder.

But to be honest, code splitting isn't really that big a deal with a desktop app, since the whole codebase is downloaded and loaded from the user's harddrive. And users are ok waiting a 4-5 seconds for a desktop app to load. Just think of the last time you opened Microsoft Word. lol.

And once both codebases are parsed and loaded into memory, you'll be back to near native speed.

Code splitting works best for webapps. So unless you're having performance issues, I think you'll be alright with a little duplication.

**Comment by momocow** [comment]
So I can consider that the `common` directory is for better maintenance (**source** code splitting only).

Conclusion:
The size of the codebase is not a concern for a desktop app, and the effort to deal with a little duplication is not worthy.

>  Just think of the last time you opened Microsoft Word. lol.

This is quite convincing. 🤣 

Thank you!

**Comment by natearmagost** [comment]
> One thing you could do is split out that code and publish it as a module.

I ended up just doing a local module, not even going through npm.

package.json:
```
  "dependencies": {
    "my-module": "file:./shared/my-module",
```

directory structure:
```bash
├── shared
│   ├── my-module
│   │   ├── index.js
│   │   ├── package.json
...
```

module's index.js:
```
const myModule = () => { return 'something; }
module.exports = myModule;
```

module's package.json:
```
{
  "name": "my-module",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  ...
```

renderer.js:
```
import myModule from 'my-module';
```

main.js:
```
const myModule = require('my-module');
```

I was running into the same issue - Duplicate code.
