### ISSUE TITLE
Starting new app using Vue

### ISSUE THREAD

**Issue by FantasticFiasco** [electron-userland/electron-webpack#2]
I was just about to start building an electron app using Vue when I came across your post on [electron-vue](https://github.com/SimulatedGREG/electron-vue/issues/252). What do you think, should I build upon electron-vue or are you close to a 1.0.0 release (assuming you adhere to semver) with this project?

**Comment by develar** [comment]
> are you close to a 1.0.0 release 

1.0 release will be as soon as @SimulatedGREG will somehow react to https://github.com/SimulatedGREG/electron-vue/issues/310 It is the only reason, why `1.0` is not yet released. 

I recommend you to use electron-webpack, because number of issues were fixed in this project, number of features were implemented (including changes on electron-builder project side).

**Comment by FantasticFiasco** [comment]
Ok then, I'll give this project a spin. Thanks for the quick response!

**Comment by develar** [comment]
You can use electron-builder slack (https://slackin.electron.build/). For quick questions/quick help it can be better ;)
