### ISSUE TITLE
Can't get JSX to work at all

### ISSUE THREAD

**Issue by stereokai** [electron-userland/electron-webpack#272]
@develar @loopmode @christophpre Please advise.

I am using the latest version of `electron-webpack`.

I have tried both with Babel by doing
```
npm i @babel/preset-react --dev
```

And with TypeScript using:
```
npm i typescript electron-webpack-ts --dev
```
together with
```json
{
    "extends": "./node_modules/electron-webpack/tsconfig-base.json",
    "compilerOptions": {
        "jsx": "react"
    }
}
```

In addition, I tried `.js`, `.ts`, `.jsx` and `.tsx` as extensions for `renderer/index.js`

Had to do `npm install` several times in the process.

Nothing worked. I keep getting this error:
```bash
  ERROR in ./src/renderer/index.ts 8:16
  Module parse failed: Unexpected token (8:16)
  You may need an appropriate loader to handle this file type.
  |         console.log("im here");
  |         return (
  >                 <h1>Hello from react</h1>
  |         );
  |     }
   @ multi (webpack)-dev-server/client?http://localhost:61604 (webpack)/hot/dev-server.js css-hot-loader/hotModuleReplacement ./src/renderer/index.ts renderer[3]
```

What gives?

**Comment by christophpre** [comment]
Hi, i just tried this with a freshly cloned **electron-webpack-quick-start** template.

In order to use react with typescript in electron webpack you need the following dev-dependencies:

`yarn add typescript @types/react @types/react-dom electron-webpack-ts @babel/preset-react --dev`

Additionally you need to 

`yarn add react react-dom`

Your .tsconfig looks correct. Additionally you need to add a file **webpack.renderer.additions.js** with the following content to the project root (see https://webpack.electron.build/modifying-webpack-configurations):

```javascript 
module.exports = {
    module: {
      rules: [
        {
          loader: "babel-loader",
          options: {
            presets: ["@babel/react"]
          }
        }
      ]
    },
    resolve: {
        extensions: ['.ts', '.tsx']
      }
  }; 
```

This needs to be referenced in the package.json as follows:
```json
  "electronWebpack": {
    "renderer": {
      "webpackConfig": "webpack.renderer.additions.js"
    }
  }
```

Rename your **index.js** to **index.tsx** and it should work. Use **.tsx** for your react components. Here is a working example: [electron-webpack-quick-start.zip](https://github.com/electron-userland/electron-webpack/files/2897783/electron-webpack-quick-start.zip) Let me know if it helped.

**Comment by stereokai** [comment]
Thank you very much, the example in your zip file does seem to work - however, instead of HMR, the entire page is reloading every time I make a change :(

**Comment by stereokai** [comment]
@christophpre ? :)

**Comment by christophpre** [comment]
As far as I've experienced, HMR usually works in electron-webpack. Due to your app architecture it may be necessary that your page is reloaded every time you make a change to certain parts in your code. HMR does not necessarily mean that your page never gets reloaded completely.

For further in info, see https://webpack.js.org/concepts/hot-module-replacement/#in-a-module:
> Similarly, when implementing the HMR interface in a module, you can describe what should happen when the module is updated. However, in most cases, it's not mandatory to write HMR code in every module. If a module has no HMR handlers, the update bubbles up. This means that a single handler can update a complete module tree. If a single module from the tree is updated, the entire set of dependencies is reloaded.

**Comment by stereokai** [comment]
Thanks for coming back. I don't have any additional app architecture, I used only the repo you provided me in the zip file.

**Comment by christophpre** [comment]
The same as said above (see https://webpack.js.org/concepts/hot-module-replacement/#in-a-module) I think applies to my example. Since there is only one react component in the example, the whole page gets updated every time you change this component, because the whole dependency tree of the page relies on this single component (I could be wrong though, I am not an expert in HMR, but that's simply how I understood it) and the changes bubble up. 

I tried this in another app, that I developed with electron-webpack, where I styled a react component with css in a separate .css file. Changing only the css in the .css file did, for instance, not reload the whole page, but applied the styling changes immediately.

**Comment by stereokai** [comment]
What you are describing happens because of css-hot-reloader :)

Have you tried in addition to modify the JS/template of a deeper components in your second app, and then see what gets reloaded?

**Comment by christophpre** [comment]
True, of course you're right, in that case the style-loader is doing the hot module replacement (https://webpack.js.org/guides/hot-module-replacement/#hmr-with-stylesheets) :man_facepalming: my bad. 

So I just tried this out with the example I have provided. I think what is actually missing is to accept HMR calls and handle those calls like described in https://webpack.js.org/guides/hot-module-replacement/#enabling-hmr.

If you add the following code in the last line of the renderer index.tsx, the HMR only bubbles up until the index.tsx and react handles the rendering of the updated code.

```javascript
if (module.hot) {
    module.hot.accept()
}
```
If you don't add this code, then you're right, the whole page would reload every time. But the question is whether this should be handled by electron-webpack, or by the app you're developing.

**Comment by stereokai** [comment]
I see. I wasn't aware HMR requires additional code - but that's good to know!

So just to make sure I understand, HMR bubbles from the edited file, up the import tree, until it hits that snippet - which defines an "HMR boundary" - meaning webpack will only reload the modules that are *imported* in the module containing the snippet - and will not reload any modules that are *importing* the module containing the snippet. Right?

**Comment by christophpre** [comment]
That's it more or less, at least as far as I've understood it, but I'm sure there's a little bitte more to it. The module containing the ```javascript module.hot.accept()``` code declares that it is responsible for handling the changes until that point and hot module propagation doesn't need to bubble up any further.

**Comment by stereokai** [comment]
What does it mean that it is responsible for handling the changes?

**Comment by christophpre** [comment]
```module.hot.accept()``` tells the HMR that all changes up till now will be handled. From https://webpack.js.org/api/hot-module-replacement/#accept-self (which is what we used):

> When this module or dependencies are updated, this module can be disposed and re-evaluated without informing parents. This makes sense if this module has no exports (or exports are updated in another way).

There is even a callback in the accept method, where you can explicitly handle changes:

From https://webpack.js.org/api/hot-module-replacement/ (Please read for further info)
```javascript
if (module.hot) {
  module.hot.accept('./library.js', function() {
    // Do something with the updated library module...
  });
}
```

**Comment by stereokai** [comment]
Thank you :)
