### ISSUE TITLE
How do we inspect electron (how to pass the --inspect-brk option)?

### ISSUE THREAD

**Issue by trusktr** [electron-userland/electron-webpack#284]
It's not clear how to do this with electron-webpack.

**Comment by loopmode** [comment]
First we have this line: https://github.com/electron-userland/electron-webpack/blob/ae2a2f1ab3f2671831eb08169ee1d20aa00dfbb6/packages/electron-webpack/src/dev/dev-runner.ts#L61

So, we can set a `ELECTRON_ARGS` env. 
If we don't, the next line kicks in and sets a default: https://github.com/electron-userland/electron-webpack/blob/ae2a2f1ab3f2671831eb08169ee1d20aa00dfbb6/packages/electron-webpack/src/dev/dev-runner.ts#L62

As you can see, however, the `ELECTRON_ARGS` is being JSON parsed, which caused me some trouble getting this to work..

This one works - directly from the commandline when there is a `"dev": "electron-webpack dev"` script in package.json:

```
ELECTRON_ARGS=[\"--inspect-brk=9229\"] yarn dev
```

- If we don't put the brackets around it, the code fails with `args.push is not a function` - because it will be a string instead of an array.
- If we don't escape the quotes, the code fails with `Unexpected number in JSON` because.. well.. `JSON.parse('--')`

I really couldn't make it work _inside_ the script, e.g. I tried many variations similar to `"dev": "cross-env ELECTRON_ARGS='[\"--inspect-brk=9229\"]' electron-webpack dev"`, but I couldn't work around the parsing errors at all.

However, the first mentioned variant does work.

**Comment by loopmode** [comment]
Aha. There is a much simpler way actually :) 

Since `electron-webpack` uses `dotenv` already, you are free to specify the `ELECTRON_ARGS` in a `.env` file - or preferrably in a `.env.development` file, and there you don't need to care about escaping stuff:

```
# file: .env.development
ELECTRON_ARGS=["--inspect-brk=9229"]
```

Then simply start development as usual, e.g. `yarn electron-webpack dev` (or `yarn dev` if you have it in package.json)

**Comment by loopmode** [comment]
Added documentation about this via https://github.com/electron-userland/electron-webpack/commit/d2cf30761e8e8cedfe54bee6093c1e305a0f23bc
