### ISSUE TITLE
add exclude field to css rule... using the already implemented merge.smart... how?

### ISSUE THREAD

**Issue by UXDart** [electron-userland/electron-webpack#287]
Hello. I want to add exclude /node_modules/ to the already rule of css, so I have a custom config with:

```
  module: {
    rules: [
      {
        test: /\.css$/,
        exclude: [/node_modules/]
      },
```

but it adds a second css rule, what I'm missing? TIA

**Comment by loopmode** [comment]
Currently,  the webpack-merge smart strategy is hard-coded and prevents this. If you study it's documentation,  you might figure out how to merge instead of replace the loader, however it's besides the point that this is a flaw in the electron-webpage setup.
There are several issues around this topic, and a PR that would help out by allowing us to manipulate the config manually: https://github.com/electron-userland/electron-webpack/pull/254 just merged, but not released yet.
It will allow you to provide a custom e.g. `webpack.renderer.additions.js` that exports a function instead of an object. That function receives the full config, and should export the full config after you manipulated it.
I hope @develar will publish a new version soon. I will contact him as well and ask for permission/credentials so I can release new versions too.

**Comment by UXDart** [comment]
awesome, thanks! that merge/PR would be a great solution indeed, thanks 👍

**Comment by UXDart** [comment]
what about release a beta? like 2.6.3-beta1? or something like that... so that way we can start using it but at the same time no one is saying that there is a new release stable or anything... I understand someone else needs to decide this, but just saying having a version on npm would help. TIA!

**Comment by loopmode** [comment]
I spoke to @develar about this. There will be release soon, and in future I too will be able to publish new releases. However, right now there are some failing tests - probably unrelated to this particular PR - that need to be sorted out first, and by him (because I'm on windows and the test never worked for me, I'll have to invest some time until I can rely on the test suite and publish new versions)

**Comment by mjashanks** [comment]
Hi. I just created #291 which i think is relevant to this conversation. Allows us full use of the webpack-merge api.

**Comment by loopmode** [comment]
Hi @UXDart

2.7.2 was released today and it supports a function as config, which allows you to modify loaders as needed.

Have a look at this example where I already filter for the style loaders and then mutate their settings. I'm sure you'll find your way around based on the code snippet: https://github.com/electron-userland/electron-webpack/issues/296#issuecomment-504652118

Otherwise please reopen this issue!
