### ISSUE TITLE
Single webpack conf for both main and renderer process

### ISSUE THREAD

**Issue by fabiospampinato** [electron-userland/electron-webpack#290]
I'd like to have a single webpack configuration for both main and renderer process, but I want to pass different options to some plugins depending on if we are currently compiling for the main process or the renderer process.

Is there a way to know what process we are compiling?

**Comment by loopmode** [comment]
You can define separate configs for renderer and main in electron-webpack config. (See https://webpack.electron.build/configuration)
There you could extend a single (third) config as needed.

However, note that until next release the resulting configs will still be merged on top of the internal config using the "smart" strategy from `webpack-merge`.

**Comment by fabiospampinato** [comment]
@loopmode that's what I'm currently doing, but I'd like to have just 1 file instead of 3.

**Comment by loopmode** [comment]
I see. Nevermind my edit :)

**Comment by fabiospampinato** [comment]
@loopmode Thanks anyway for the help!

**Comment by loopmode** [comment]
@fabiospampinato looking at the code, the configurator instance does have an `isRenderer` field, but that's not available to us when we are in the actual config file.

Now that we merged the PR https://github.com/electron-userland/electron-webpack/pull/254 however, we can and should provide this info. The PR allows us to provide a function instead of an object as config - so we should pass such additional info into the function as second argument. Might be as easy as passing `this`, the configurator object.

For now...you could loop over the `entry` and check if it contains "renderer/" or "main/" - bit of manual work, but I think it should work reliably.

**Comment by mjashanks** [comment]
Hi there, I just made a PR (#291) that gives us access to the full webpack-merge api. I think it should cover of this issue (i.e. no longer restricted to the "smart" strategy only.

Would like to get this merged in :)

**Comment by loopmode** [comment]
Hi @fabiospampinato, 2.7.2 was released today, and while the docs haven't been updated yet, what you request here is now possible!

- you can have a single config for all cases
- your config should export a function and not an object
- the function receives the config object as first argument and should return the final config after modifications
- the second argument is the configurator object itself, it has `isRenderer` and `isProduction` properties.

Feel free to console.log the arguments inside the config function, you should find everything you need.

Please reopen if something is still missing.

**Comment by fabiospampinato** [comment]
Awesome, thank you!
