### ISSUE TITLE
Customize dev and production build

### ISSUE THREAD

**Issue by techterbium** [electron-userland/electron-webpack#295]
Hello, thank you for the wonderful library. Its making life much easier. 

I want to load a specific plugin in production mode but not in dev mode. As per documentation, we can customize renderer and main process configurations but I do not see a way to customize dev and prod webpack process. 

Can someone help here?

**Comment by loopmode** [comment]
Hi @techterbium!

You can totally do this, and there are a couple of ways how to do it.

Currently, you must check for NODE_ENV manually. 
I tried `console.log(process.env.NODE_ENV)` inside a `webpack.renderer.js`.
It prints `"development"` when I run `yarn dev`.
It prints `undefined` when I run `yarn dist` or `yarn compile`.

So effectively you can check for `process.env.NODE_ENV === "development"` to know that you are in dev, and otherwise you're in prod.

Keep in mind that since 2.7.0, instead of an object, you can export a function as webpack config. It receives the config object and should return a new config object. You can mutate the given config or return a new one altogether, for example depending on the NODE_ENV.

I just commited a change and started a discussion [here](https://github.com/electron-userland/electron-webpack/commit/c6479ea3432b56b4f4f98d86461ff0476d9b923c), which would make this easier and more explicit in future versions. In that scenario, the config function would receive a second argument - an object containing all relevant information you might need.

**Comment by loopmode** [comment]
Hi @techterbium! 2.7.2 has been released and provides the configurator as second argument to a config function. The first argument is the webpack config object, while the second argument is the configurator itself - it has a `isProduction` property you can access. Will soon update the documentation to reflect this as well.

Closing this issue, please reopen if something is missing.

**Comment by techterbium** [comment]
Thank you very much @loopmode. I will try this and get back to you in case of any issues.
