### ISSUE TITLE
js-yaml which is a dependency of electron-webpack has security Issues

### ISSUE THREAD

**Issue by superhit0** [electron-userland/electron-webpack#300]
* **Version**:  `2.7.2` also saw same issue in `2.7.1`

This is the git project I am using electron-webpack in https://github.com/superhit0/day-n-night.
I am getting security Issues alert in it.
please help Thanks

* **Target**:

**Comment by loopmode** [comment]
@superhit0 Thanks for reporting this. Unfortunately, we cannot fix this easily - but you can, in your own project!

So, first things first: js-yaml isn't a direct dependency of electron-webpack, it's rather a sub-dependency:
```
$ yarn why js-yaml
yarn why v1.16.0
[1/4] Why do we have the module "js-yaml"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "js-yaml@3.13.1"
info Has been hoisted to "js-yaml"
info Reasons this module exists
   - "workspace-aggregator-a2ddcdcc-a06a-4a3e-b27c-f57d5e949094" depends on it
   - Hoisted from "_project_#tslint#js-yaml"
   - Hoisted from "_project_#electron-webpack#read-config-file#js-yaml"
   - Hoisted from "_project_#electron-webpack-eslint#eslint#js-yaml"
   - Hoisted from "_project_#electron-webpack#html-loader#htmlnano#svgo#js-yaml"
=> Found "postcss-svgo#js-yaml@3.7.0"
info Reasons this module exists
   - "_project_#electron-webpack#html-loader#htmlnano#cssnano#postcss-svgo#svgo" depends on it
   - Hoisted from "_project_#electron-webpack#html-loader#htmlnano#cssnano#postcss-svgo#svgo#js-yaml"
Done in 1.06s.
```

Next thing is: yes, we could start upgrading our own dependencies, but if they haven't upgraded yet, it won't help. In fact, we are doing upgrades of our dependencies every now and then, so eventually this will "go away on its own".

Now - of course that is no satisfactory solution to just wait. But: You can help yourself!

This second part also has a "first" and a "next" thing :)
First thing is: Are you using npm and not yarn? Because npm tends to report those vulnerabilities while yarn doesn't. If that's the case, then you should switch to yarn, at least for this project and situation.

Next thing is: Yarn has a feature where you can specify which version of a dependency or sub-dependency should be used, despite of what some other dependencies may have specified.
That's the [selective version resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) feature.
Concretely, since js-yaml has fixed it vulnerability in [version 3.13.1](https://github.com/nodeca/js-yaml/blob/master/CHANGELOG.md#3131--2019-04-05), you would add this to your package.json:
```
"resolutions": {
    "js-yaml": "3.13.1"
  }
```
If you have a lockfile (which you have if you use yarn, yarn.lock), you might have to delete it, as it will contain the various used versions and try to install them again. Also delete your node_modules.
Next time you run `yarn` (or `yarn install`), js-yaml will be installed in version 3.13.1 for all dependencies - and hopefully not break any of them :)

If you already use yarn, and you got the vulnerability warnings from github, well it's the same thing basically - specify a resolutions version - but even if your app wouldn't be vulnerable, you might not be able to get rid of the warning.

I hope this helps. And in case you come from a serious language and are new to the javascript/node community... Unfortunately, ignoring warnings is part of our everyday life :)

Btw, afterwards, it looks like this:

```
$ yarn why js-yaml
yarn why v1.16.0
[1/4] Why do we have the module "js-yaml"...?
[2/4] Initialising dependency graph...
warning Resolution field "js-yaml@3.13.1" is incompatible with requested version "js-yaml@~3.7.0"
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "js-yaml@3.13.1"
info Reasons this module exists
   - "read-config-file" depends on it
   - Hoisted from "read-config-file#js-yaml"
   - Hoisted from "electron-builder#app-builder-lib#js-yaml"
   - Hoisted from "electron-webpack#read-config-file#js-yaml"
   - Hoisted from "electron-builder#builder-util#js-yaml"
   - Hoisted from "electron-builder#dmg-builder#js-yaml"
   - Hoisted from "electron-webpack#html-loader#htmlnano#svgo#js-yaml"
   - Hoisted from "electron-webpack#html-loader#htmlnano#cssnano#postcss-svgo#svgo#js-yaml"
Done in 0.90s.
```
And everything works fine.

**Comment by develar** [comment]
1. Use workaround as amazing @loopmode suggested (`resolutions`).
2. Use electron-builder `^21.0.11`
3. I released a new version of electron-webpack with updated dependency on `read-config-file`.

Still, I cannot fix external depedency `svgo`:

```
yarn why v1.17.0
[1/4] 🤔  Why do we have the module "svgo"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "svgo@1.2.2"
info Reasons this module exists
   - "electron-webpack#html-loader#htmlnano" depends on it
   - Hoisted from "electron-webpack#html-loader#htmlnano#svgo"
info Disk size without dependencies: "580KB"
info Disk size with unique dependencies: "5.25MB"
info Disk size with transitive dependencies: "8.54MB"
info Number of shared dependencies: 38
=> Found "postcss-svgo#svgo@0.7.2"
info This module exists because "electron-webpack#html-loader#htmlnano#cssnano#postcss-svgo" depends on it.
info Disk size without dependencies: "436KB"
info Disk size with unique dependencies: "3.31MB"
info Disk size with transitive dependencies: "7.18MB"
info Number of shared dependencies: 21
```

**Comment by loopmode** [comment]
@develar according to https://stackoverflow.com/a/49126573/368254 you can target child dependencies explicitly with ** - haven't tried it, but then again, finally the syntax in official examples like https://yarnpkg.com/blog/2018/02/15/nohoist/#how-to-use-it makes sense!

**Comment by zeebenzene** [comment]
I came across this same thing when I ran yarn audit.  The nice thing about the output of yarn audit is that it shows you the dependency tree:
**electron-webpack > html-loader > htmlnano > cssnano > postcss-svgo > svgo > js-yaml** 

After looking at the issues in each of these projects I believe that the issue has been fixed up until the latest version of cssnano.  However I wasn't able to find whether **htmlnano** or **html-loader** had upgraded their packages but I didn't find any issues about **js-yaml**.  Perhaps those are less maintained.   

However adding this to my package.json like mentioned above and running `yarn install` worked like a charm and the next time I audited there were 0 vulnerabilities. 
~~~~
"resolutions": {
    "js-yaml": "3.13.1"
  }
~~~~

**Comment by Jack-Barry** [comment]
Looks like the pull request to upgrade is in limbo right now: https://github.com/cssnano/cssnano/pull/827

**Comment by meszaros-lajos-gyorgy** [comment]
So it's been half a year now and the issue still exists. Any chance on reopening this ticket and have another round with updating dependencies?

I don't use yarn in my projects and it sounds quirky, that the solution only works in one package manager, but not in the other.

Also, if the issue still stands with dependencies and they don't want to update their repo to resolve the security issues, then just migrate to a different module.

Tracing back the dependency tree in reverse order for documentation on why the process is halted:
cssnano is okay
htmlnano, using the latest cssnano, is okay
html-loader - they are not updating htmlnano, probably accidentally closed the ticket: https://github.com/webpack-contrib/html-loader/issues/199

**Comment by meszaros-lajos-gyorgy** [comment]
Another info is that the project is using the Alpha version from the next branch, which was probably incorrectly published, since according to the author is not ready yet.
https://github.com/electron-userland/electron-webpack/blob/master/packages/electron-webpack/package.json#L37

Can anyone try and "downgrade" the module to **0.5.5**?

**Comment by meszaros-lajos-gyorgy** [comment]
According to the author of html-loader, there will be a proper 1.0.0 version coming out in the near future, which will solve this issue too, should keep an eye out for that, if you guys don't want to "downgrade": https://github.com/webpack-contrib/html-loader/pull/201
