### ISSUE TITLE
Preload Script not working when MSI is generated

### ISSUE THREAD

**Issue by bynho** [electron-userland/electron-webpack#321]
* **Version**:  21.2.0

* **Target**: MSI

I am using electron-webpack to build the distribution MSI for my app however when the app is packed it cannot find the preload.ts script which loads fine while running it in Dev mode.  Does anyone have any ideas?
I have unpacked the asar file and can see that there isnt any preload.js file, just main.js and renderer.js

The error is:
Unable to load preload script:
C:\path-to-app\app.asar\preload.ts

Error: ENOENT, preload.ts is not found in 
C:\path-to-app\app.asar

This is how I am creating the BrowserWindow:

`
this.win = new BrowserWindow({
            frame: this.useFrame,
            width: bounds.width,
            height: bounds.height,
            minWidth: bounds.width,
            minHeight: bounds.height,
            x: bounds.x,
            y: bounds.y,
            show: false,
            titleBarStyle: "hidden",
            webPreferences: {
                nodeIntegration: false,
                nodeIntegrationInSubFrames: false,
                nodeIntegrationInWorker: false,
                preload: path.resolve(__dirname, `preload.ts`),
                contextIsolation: true,
                sandbox: true,
                enableRemoteModule: false,
                disableBlinkFeatures: "Auxclick"
            }
        });
`

**Comment by loopmode** [comment]
Just a feeling but..Try .js instead of .ts file.
It will try to load this file at runtime and ts wont work then, it must be compliled.
Maybe your current file actually exists in the asar, but it was transpiled/compiled already and now has a js extension. 
I would recommend using a plain js file for preload scripts in general.

**Comment by bynho** [comment]
Thanks for your reply. I have tried js and also checked the packaged asar and cannot see preload.js.  My guess is it is being bundled into one of the webpack output bundles, and as it's trying to find the actual file it's failing.

**Comment by loopmode** [comment]
Hi @bynho 
I just remembered that I had this problem myself once, and actually solved it. Maybe it's just a workaround, but I think it actually is a proper solution.

So the problem is that webpack only cares about the dependency graph. That is, require and import statements. The script preloading however bypasses that entirely, it just defines which file to load - at runtime. 

The solution is to use the [static assets feature](https://webpack.electron.build/using-static-assets) of electron-webpack.

It's a feature that allows certain files to be bundled into the final asar regardless of whether they are part of webpack's dependency tree.

So you would place your preload script into a folder `static/` (next to `src/`) and use it from there. You'd either have to compile it seprately/somehow with `tsc`, but I would recommend simply using a js file for this.

You would then use it like this `{ ..., preload: path.resolve(__static, 'preload.js'), ...}`. 
Electron webpack provides a global `__static` variable and replaces it with an actual path to the file inside of the asar.

**Comment by bynho** [comment]
Thanks @loopmode , that has sorted it out
