### ISSUE TITLE
vulnerabilities issue found on dependency : electron-webpack > htmlnano > .... js-yaml

### ISSUE THREAD

**Issue by jega-ms** [electron-userland/electron-webpack#337]
I've integrated the electron Webpack to build a desktop application.  I could see vulenerabilites issue on dependency library. Could you please remove or upgrade dependency library ?

Sample Project : https://github.com/jega-ms/reactjs-electron-webpack 

<img width="572" alt="Screen Shot 2019-11-25 at 4 42 28 PM" src="https://user-images.githubusercontent.com/15880838/69589916-96f55300-0fa2-11ea-96da-c4dedfdecb8b.png">

**Comment by loopmode** [comment]
For now, you can work around the problem.

- use yarn instead of npm
- add this to your `package.json`:
```
"resolutions": {
    "js-yaml": "3.13.1"
}
```
- run yarn install. Potentially remove `yarn.lock`

Also, please consider using the search before creating new issues in open source projects - chances are, you're not the first one to experience the issue: https://github.com/electron-userland/electron-webpack/issues/300

**Comment by jega-ms** [comment]
Thanks
