### ISSUE TITLE
2 instances of react running

### ISSUE THREAD

**Issue by geoctrl** [electron-userland/electron-webpack#358]
* **Version**: `^22`

* **Target**: `NSIS`

### Problem

I'm using react, and I'm running into the [`invalid hook call`](https://reactjs.org/warnings/invalid-hook-call-warning.html) error. After process of elimination, I traced it to the [`kremling`](https://github.com/CanopyTax/kremling) module I installed.

However, I'm hesitant to say this is a "kremling issue" because kremling doesn't bundle react. It uses babel to transpile, and then spits out all the output files (no bundling). In the code, all it does require react. 

### Steps taken to fix:

- used `npm ls react` to find duplicate `react` modules (no duplicates found)
- did a manual `find` to look for duplicate `react` directories (no duplicates found)
- used npm module `find-duplicate-dependencies` (no duplicates found)
- added resolutions to `package.json` (didn't work) eg:
```javascript
resolutions: {
  "react": "^16.13.1",
  "react-dom": "^16.13.1",
},
```
- added aliases to `webpack.renderer.js` (didn't work)
```javascript
  config.resolve.alias = {
    ...config.resolve.alias,
    'react': path.resolve(__dirname, 'node_modules/react'),
    'react-dom: 'path.resolve(__dirname, 'node_modules/react-dom),
  };
```

ideas came from this [thread](https://github.com/facebook/react/issues/13991)

### Reproducible

I decided to isolate the problem further and created 2 repos:

#### Using bare-bones electron-webpack:

https://github.com/geoctrl/kremling-duplication-bug-electron

Following the steps given in the repo, you can see that requiring `kremling` adds a 2nd instance of react.

#### Using bare-bones web app:

https://github.com/geoctrl/kremling-duplication-bug-web

Doing the same thing here, `kremling` **does not** create a 2nd instance of react...

### Any thoughts?

I've been staring at this issue for 2 days now, and I'm unsure who should own this issue... electron-webpack? webpack? babel? kremling? 🤦‍♀

**Comment by geoctrl** [comment]
looks like white-listing `kremling` fixes this issue:

https://webpack.electron.build/configuration.html#white-listing-externals

**Comment by jordymeow** [comment]
How did you trace it to kremling? I am having the same issue, except I am getting only this error when I include external components (from an external directory). I tried whitelisting it but it didn't help - I would like to be able to debug a bit more.

**Comment by jimmed** [comment]
I just came across the same issue, but the library I needed to mark as external was `@chakra-ui/core`, rather than `kremling`.

@jordymeow I traced this by:

1. Start `electron-webpack dev`
2. Open the renderer dev tools, and find two identical log statements fired by the two versions of `react-dom` being loaded. I used the "install the React dev tools" logs.
3. Put a breakpoint at the start of each instance of `react-dom.development.js` and restart the renderer.
4. Navigate back up the call stack to find which module was importing `react-dom`, and then continue(unpause) the renderer. Repeat for the other instance of react-dom.
5. One of the instance of `react-dom` will be imported by your renderer entry point, the other will be the module you need to mark as external.
