### ISSUE TITLE
As of version 2.8.2, does it work with Yarn Workspaces?

### ISSUE THREAD

**Issue by jordymeow** [electron-userland/electron-webpack#379]
* **Version**: 2.8.2

Hi,

I have tried to make it work with Yarn Workspaces, but I ran into a gazillion of errors. I would be disappointed by a _no_ but that would also avoid me (and maybe other users) to look for a solution.

Thanks :)

**Comment by loopmode** [comment]
You mention 2.8.2 specifically - is there a reason for that? Did you get it working with an older version and it breaks now?
I did successfully set up workspaces a couple of times, and somewhere I have a repo where a create-react-app and an electron-webpack app both share common components and other modules. I think it should be still working.
However and indeed it was not trivial due to the mentioned gazillion of issues. No promise for quickness but I'll try to find and post it.
Here's something marked WIP using 2.7.4:
https://github.com/loopmode/electron-webpack-workspace-cra but the WIP there means it might not even be working. The successful setup was for a work project and it's not on GitHub, but I'll see what I can do.

**Comment by jordymeow** [comment]
I wanted to make it clearer by mentioning the version, if in the future, somebody read this :)

Actually I found your repo earlier (before you replied to this message) and decided to contact you directly. It's a bit out of the scope of this; have you received it? Otherwise, you can send me a hi through https://contact.meow.fr/ :)

My actual setup is actually a bit more complex, and I am looking for the best way to do organize a project. I actually might be wrong but there is nobody around me to tell me so :)

**Comment by loopmode** [comment]
Hi @jordymeow
Yeah I got your email. Will respond there.

**Comment by jordymeow** [comment]
Thanks a lot @loopmode :) I am closing this issue.
