### ISSUE TITLE
babel-plugin-styled-components not processing css attribute at all

### ISSUE THREAD

**Issue by UXDart** [electron-userland/electron-webpack#407]
last one

osx on dev mode

I'm using babel-plugin-styled-components, I checked and it is indeed part of the module.rules being used
but if I use a css attribute is not being converted, is anyone using styled css attributes? any idea of what config coube be missing? TIA

**Comment by UXDart** [comment]
it seems is because of the use of mini-css-extract-plugin... is there anyway to dont use mini-css-extract-plugin? anyone? thanks

**Comment by loopmode** [comment]
You can provide a custom webpack config function then remove the plugin from the plugins array. You'd iterate to find it, and then just splice the array, or replace the array by a filtered one without the plugin.

**Comment by UXDart** [comment]
thanks, it didn't work, it seems is because of the use of ts-loader, no one is using styled component babel plugin? is not possible to make it work? thx
the thing is the plugin is for babel, and ts-loader is not using it, so tsx files are not being passed by the babel plugin for some reason

**Comment by UXDart** [comment]
after a many tests the solution is to add it to the white list:
```
    "whiteListedModules": [
      "styled-components"
    ]
```

**Comment by loopmode** [comment]
Ooooooh how I hate that whitelisting topic.. what a silly cause of so much trouble :) but I've ranted enough about it in other comments. 
Glad you're not blocked by this anymore!

**Comment by shahkeyur** [comment]
> Ooooooh how I hate that whitelisting topic.. what a silly cause of so much trouble :) but I've ranted enough about it in other comments.
> Glad you're not blocked by this anymore!

I just noticed this topic and I had a suggestion, if this can be added somewhere in docs like troubleshooting section, that mentions about this problem would be really really helpful for beginners. Personally I had this issue last year and it took me way way much longer time to solve this. It's not just about any particular library but it happens if you do not whitelist all those dependencies, like auth0-lock, redux-forms and many others. And honestly as beginner at that time I wasn't able to figure out why whitelistdModules is even there.

**Comment by loopmode** [comment]
Yep it's hard to grasp as a beginner but also in general since it's a sort of negated rule ("do not add these packages to webpack externals").

Indeed there should be a troubleshooting section. Volunteers welcome :)

My personal recommendation for now is to use a custom webpack config function and set externals to an empty array during project setup.

This basically resets whatever the whitelisting feature did previously, and makes it the user's responsibility to manage externals where needed.
