### ISSUE TITLE
document is not defined in production

### ISSUE THREAD

**Issue by brandoncc** [electron-userland/electron-webpack#45]
I am using react to build my application. I use `document` in `src/renderer/index.js` to create a node and render my app. I am also using [react-hot-loader](https://github.com/gaearon/react-hot-loader), which requires me to override the webpack entry point.

My `webpack.renderer.additions.js` file looks like this:

```javascript
module.exports = {
  entry: [
    'babel-polyfill',
    'react-hot-loader/patch',
    './src/renderer/index.js'
  ],
  resolve: {
      extensions: ['.js', '.jsx']
  },
  module: {
    rules: [
      {
        test: /\.jsx?$/,
        loader: 'babel-loader',
        options: {
            presets: ['react']
        }
      }
    ]
  }
}
```

This works great in development, but it doesn't work in production. When I run my generated `.app` file, I get a "document is not defined" error. As soon as I remove the `entry` portion, everything works fine. I assume a different entry point needs to be set during production builds, but I haven't figured out what it is or how to do it.

Thanks in advance!

**Comment by walleXD** [comment]
you can just include `import 'react-hot-loader/patch'` on the top of your index file. That way you can avoid adding custom Webpack config. Give that a shot and see whether it works or not

**Comment by brandoncc** [comment]
At first glance that appeared to work, until I realized that even though the console said the hot loader was updating the changed modules, the changes didn't actually happen on the page.

```
[WDS] App updated. Recompiling...
[WDS] App hot update...
[HMR] Checking for updates on the server...
[HMR] Updated modules:
[HMR]  - ./src/components/Login.jsx
[HMR] App is up to date.
```

This is from the console, but no changes occur as they do when I use the webpack entry configuration.

**Comment by brandoncc** [comment]
Actually, I just tried making the same change when using the entry configuration and I got the same result. I'll comment again when I figure this out. Thanks 👍

**Comment by brandoncc** [comment]
@walleXD That worked perfectly, thank you. I ended up needing to change the `"env"` preset in `.babelrc` to `["env", { "modules": false }]`, which is what was breaking the hot loading in my previous comment.

**Comment by navono** [comment]
@brandoncc Can you explain the final solution or show some config? I encounter the same problem when I use custom webpack config. Thank you.

**Comment by loopmode** [comment]
@navono `["env", { "modules": false }]` basically tells babel to use "native es6 modules" and NOT compile everything into commonjs modules first.

Not sure how helpful this explanation is, but it seems related: I first needed that setting when switching to webpack 2 and wanted treeshaking.
Webpack was unable figure out which exports are used and which ones can be dropped, because in commonjs, all es6 exports become part of the single `module.exports` object. Elsewhere that entire object is required and some of its properties are being referenced. Basically `export {foo, bar}; export {baz}` becomes something like `module.exports = {foo, bar, baz /* everything is in here*/}`. 

The use cases seem to be somewhat related: Both treeshaking and HMR need good static analysis of dependencies, which seems work well es6 modules while it's difficult or impossible with commonjs modules.
