### ISSUE TITLE
Always looking for index.ts (or .js)

### ISSUE THREAD

**Issue by YonatanKra** [electron-userland/electron-webpack#49]
I've added `electron-webpack` to an existing project.
My main file is `src/app.js`, so I've setup my config like this:
```
"electronWebpack": {
    "commonSourceDirectory": "./resources",
    "title": true,
    "main": {
      "sourceDirectory": "src",
      "webpackConfig": "custom.webpack.additions.js"
    },
    "renderer": {
      "sourceDirectory": "resources"
    }
  }
```
In `custom.webpack.additions.js` I've setup a simple entry field:
```
module.exports = {
    entry: "/src/app.js"
};
```
While trying to pack: `electron-webpack` I get the following error:
`Error: Cannot find entry file src\index.ts (or .js)`

Why doesn't my config take the entry I've specified?
Thanks

**Comment by YonatanKra** [comment]
I've validated that the custom webpack file is taken into consideration, because when I remove `app.js` it does say it is missing. 
It seems like that the `custom.webpack.additions.js` is taken as an addition to what is defined in the `sourceDirectory` property.  
This probably happens because `applyCustomModifications` fires after trying to get the entry from the original config.
Is this a bug? Or intentional?

**Comment by develar** [comment]
`app.js` or `app.ts` are added to search list (in addition to main or index).

**Comment by loopmode** [comment]
@develar @SimulatedGREG I don't have the full picture, I just wanna remind you of something:

By now, we can extend the webpack config and under the hood, `webpack-merge` is used with its smart strategy: 
https://github.com/electron-userland/electron-webpack/blob/dd2a369ec27cad13d30b94844d6ece28c8a4eb29/packages/electron-webpack/src/main.ts#L236-L248

And `this.applyCustomModifications()` is happening right after the operations just submitted with https://github.com/electron-userland/electron-webpack/commit/dd2a369ec27cad13d30b94844d6ece28c8a4eb29

Shouldn't we, the users, be already able to control the entry points via custom config? 

As I mentioned earlier in a `feat/custom-config` discussion elsewhere, we should allow users to specify a merge strategy, and then we might get around hardcoded handling of entry points entirely, see https://www.npmjs.com/package/webpack-merge#merging-with-strategies

**Comment by develar** [comment]
I really don't want to make electron-webpack to be like WiX toolset. God save me. So, even, even if will be and there is an easy way to configure extra entry points, in any case we DO provide `main.extraEntries` and we DO some magic under the hood if it will not affect other users.

`app` looks ok for me as a possible entry point and so, no need to force users to learn how to use this file name. It is not our business for what and why `main` or `index` is not suitable.

> Shouldn't we, the users, be already able to control the entry points via custom config?

I can answer — yes, users should be able to use this way. But problem is that right now I am not sure that will work. Please see #47 Do you see? Yes — problem is that in addition to entry file name, probably some other not simple to write configuration should be added to make it really working. I am not sure how is complex such configuration in case of renderer, but... in any case #47 will be solved as a new option `renderer.extraEntries`. Not as docs "add these f*** magic lines and it will work". I am still not sure (need to investigate), but though.

**Comment by loopmode** [comment]
Totally understand your point there. Just seems popular in the last days to try and use electron-webpage for non-SPA apps. I personally think one entry point is enough - everything else can be handled via code from there (as opposed to via config)

**Comment by walleXD** [comment]
@loopmode I spent a good couple of hours messing around with the programatic approach to get a second renderer working. I got it work to the point where it messes up the existing renderer since there's no way for me to leverage the dynamically generated html template used for it. Also, the current renderer is setup to load all files from webpack entries. This complicates the situation even more as even if I programmatically add a second entry point and setup the proper html generation, I will also have to scrap what `electron-webpack` generates entirely for the renderer since the main renderer will be including the newly added entry point too. So, what this ends up being is that we would need to re write most of the renderer pipeline to use multiple renderers. On the other hand, adding extra renderer entries into electron-webpack would mean that the same build pipeline can be used to build both entries while just making sure each html page includes only one of the entries files. So, that when I wrote up #47
