### ISSUE TITLE
using electron-compile with different ui/pages based on cli args or remote urls

### ISSUE THREAD

**Issue by joelharkes** [electron-userland/electron-webpack#5]
Im trying to build an app that does stuff on the computer.

The app can do multiple actions and has a CLI interface and remote url protocol (electron://).

also based on CLI command arguments or remote url i want to show different ui/page or not even an ui at all.

How would i go about this in electron-webpack? it seems like mi forced very much into 1 main entry point and one renderer entry point. is this correct? is there a way i could make my app work with this package?

**Comment by joelharkes** [comment]
It would be nice that project structure wouldn't be so strict, but configurable and understandable. now its more like magic. (maybe show how to configure directly webpack for entrypoints)

**Comment by develar** [comment]
You can add additional main entry points:

add following code to `package.json`:

```json
"electronWebpack": {
  "main": {
      "extraEntries": ["@/foo.js"]
    }
}
```

(`@` it is alias to source root, no need to write here full or relative path, just use `@`).


> one renderer entry point

I am working right now to allow to use `yarn dev` without renderer process. For now, you can compile your project using `node_modules/electron-webpack/webpack.main.config.js` [configuration file](https://github.com/electron-userland/electron-webpack/wiki/Configuration-FIles).

**Comment by develar** [comment]
`dev` command doesn't required render sources to be presented.
```
┏ Renderer -------------------

  No renderer source directory (src/renderer)

┗ ----------------------------
```

will be printed instead.

Docs about main entry points added.

`yarn compile` still requires renderer. You can use provided configuration file for main as workaround, but it will be fixed in 2 days. Issue because if that is still opened.

**Comment by joelharkes** [comment]
develar, i decided to use webpack directly instead to have more freedom. 
Im wondering about one thing though. how did you get it to work that it even hotloads the main process?

I see renderer processes are loaded over localhost:[webpackDevServerPort] 
but how would you do that for the main process?

**Comment by develar** [comment]
> instead to have more freedom

If you want to reiterate all hard work that was put by @SimulatedGREG and me — go ahead :) 

Current limitations — just reflects that this project was result of https://github.com/SimulatedGREG/electron-vue/issues/310 Nothing more.

You can add additional main entry points.

Renderer is not required now, by your request. `compile` task not fixed yet, but you are not restricted — no magic here. Just use webpack as you want using provided configuration files (https://github.com/electron-userland/electron-webpack/wiki/Configuration-FIles) You are not forced to use provided `electron-webpack` CLI. Just point webpack to provided configuration file and use webpack CLI as you want.

If you want to change project structure and want to use `foo/bar` instead of `src/main` — just file issue and feature will be done in a short term. Several configuration options vs "write own webpack configurations for 2 process, debug and test it, maintain, write electron-builder configuration"

> how did you get it to work that it even hotloads the main process?

electron-webpack contains own HMR implementation for node. It is part of electron-webpack, because  in addition to client side (injected as multi entry point to your code), server side is required (and it is part of electron webpack dev runner).

**Comment by joelharkes** [comment]
I understand and i find it too, but your project really pushed people in a certain direction/structure. 
instead of it being a framework in which you build your project it would be much nicer to be, more like a library you can include in your project and configure to your needs. 

I undersetand your concern of reiterating hard work but for me so far it has always been that once a framework pushes you too much in a direction that you are pretty sure you wont follow, to not use it or you will end up with problems later-on.

**Comment by develar** [comment]
> but your project really pushed people in a certain direction/structure.

Only because source dirs for main and renderer is not configurable. And it will be fixed (nearly ready to push). Do you find anything else that restrict your freedom?

> it would be much nicer to be, more like a library you can include in your project 

It is. Just use as a collection of configuration files. https://webpack.electron.build/configuration-files

**Comment by develar** [comment]
@joelharkes Thanks for feedback, please see https://webpack.electron.build/Options.html#source-directories

Not documented yet, but you can also simply use electron-webpack as a library. See `test/src/test.js`

```js
const configuration = await require("electron-webpack/webpack.main.config.js").default({production: true, configuration: {
  projectDir,
  main: {
    extraEntries: ["@/foo.js"],
    sourceDirectory: "customMain"
  },
}})
```

In the `configuration` you can pass [options](https://webpack.electron.build/options).

Resulting configuration you can use or as is, or... do whatever you want :) For example, in the tests, custom resolver is added (https://github.com/electron-userland/electron-webpack/blob/master/test/src/test.js#L73). It doesn't mean that in this case you are forced to use programmatic API of webpack instead of CLI. Because webpack allows you to do whatever you want in the config file and return promise of config.

Provided `electron-webpack/webpack.main.config.js` configuration files uses this approach, 

```typescript
import BluebirdPromise from "bluebird-lst"
import { configure } from "./src/webpackConfigurator"

export default (env: any) => BluebirdPromise.all([configure("main", env), configure("renderer", env)])
```

No magic here — it is simple JS that uses programmatic API to compute configuration and then returns to webpack.

But I hope, that declarative API (via options) will be enough for you. In any case, if something still restrict your freedom or looks not expected/intuitive — feel free to open discussion and file issue.
