### ISSUE TITLE
`/static` folder path not working in production

### ISSUE THREAD

**Issue by loopmode** [electron-userland/electron-webpack#52]
The path to the static folder (used via `__static`) doesn't work for us in the published version.
It does not get properly resolved to the runtime path, instead it keeps using the path to `/static` from development-time/compile-time.

___Example___

In development:
- Project is in `D:\projects\myproject`
- We have a file  `D:\projects\myproject\static\file.txt`
- In code, we do `fs.readFileSync(__static + '/file.txt')`
- App reads file from `D:\projects\myproject\static\file.txt`
- works!

In published app:
- App was built via `yarn dist`
- App is installed in `C:\Users\loopm\AppData\Local\Programs\myproject`
- App writes logs in `C:\Users\loopm\AppData\Roaming\myproject`
- App still reads `static/file.txt` from `D:\projects\myproject\static\file.txt` 
- fails!

Currently, we avoid using the static folder at all for this reason, doing some heavy workflows/workarounds.

- The same thing happens when building on Mac
- Can this be a usage error on our side?
- Should I set up an example repo?

**Comment by walleXD** [comment]
did the 1.11.0 release fix this issue @loopmode?

**Comment by loopmode** [comment]
Not tested yet but looks as if 1.11.0 only fixed it for main process, not yet for renderer

**Comment by develar** [comment]
Is __static is used in the CSS? Because of that fix for main is not applicable for renderer.

**Comment by counterbeing** [comment]
I'm seeing the same exact thing on mac/windows. The docs seem pretty clear on how this is intended. I'm on version 1.11.0, and trying to call it from the renderer. 

I can see my static assets copied to the resources folder on both installs.

**Comment by counterbeing** [comment]
There was a little more context here for anyone just joining: https://github.com/electron-userland/electron-webpack-quick-start/issues/2

Took me a moment to find, but their workaround seems to work for me on the Mac side, still having issues with my windows build.

**Comment by IGassmann** [comment]
Same problem here. It's also a problem for when you use `webpack-dev-server` from `electron-webpack`. The resource won't be accessible from the dev-server. Example:

- Actual path to static resource: `/Users/IGassmann/Developer/electron-webpack-project/static/example.png`
- Fetch `__static + example.png` on dev-server throws 404 HTTP error for `localhost:8060/Users/IGassmann/Developer/electron-webpack-project/static/example.png`
- Fetch `__static + example.png` on built project in the same environment get the resource without problems
- Fetch `__static +  example.png` on built project in a different environment throws NOT FOUND for
`/Users/IGassmann/Developer/electron-webpack-project/static/example.png`

Maybe it should use a relative path instead of an absolute one.

**Comment by hacker112** [comment]
@IGassmann In your case you should use file:// as prefix for the absolute paths.

---

I am using: electron-webpack version 1.12.1 and the problem still there.

In the Main process the path seems ok even though the slash in in the wrong way on windows (the path ends with /static instead of \static).

In the Render process the __static is replaced with the absolute path of the static folder that i used on the development machine, so you won't notice this until you try it on an other machine. __static can not be replaced in runtime. I made a workaround until the __static problem is solved.

Just save this as `staticPath.js` and use that instead of __static directly:

```javascript
'use strict';

// eslint-disable-next-line no-process-env
const isDevelopment = process.env.NODE_ENV === 'development';
const staticPath = isDevelopment ? __static : __dirname.replace(/app\.asar$/, 'static');

module.exports = staticPath;

```

**Comment by IGassmann** [comment]
@hacker112 unfortunately, your solution didn't work. The resulting path after the production build is an absolute path: `file:///Users/travis/build/lbryio/lbry-app/static/img/lbry-white-485x160.png`. It's then not valid when using it on other systems.

**Comment by loopmode** [comment]
weird. so `__dirname` got evaluated at compile-time and not at runtime..? 
Maybe naive, but what happens if you wrap it in a function call?

```
'use strict';

function getStaticPath() {
    // eslint-disable-next-line no-process-env
    const isDevelopment = process.env.NODE_ENV === 'development';
    const staticPath = isDevelopment ? __static : __dirname.replace(/app\.asar$/, 'static');
    return staticPath;
}

module.exports = getStaticPath;
```

Wouldn't be very ergonomic to use, but if it worked.. would be better than nothing :)

**Comment by hacker112** [comment]
@IGassmann: It works, I used it in my project. But you have to import the file `staticPath` file and not use `__static` directly. The `__static` constant will be replaced during production build but `__dirname` is dynamic and is set in runtime. @loopmode code is an alternative, but wrapping it in a function should not be needed. That the path is an absolute path is not a problem as long as it is dynamically creating during runtime so that it is correct on the running system.

**Comment by IGassmann** [comment]
@hacker112 oh yes, checking if it's a dev environment or not works. I was already previously doing this. I thought that by using `file://` it would let me get rid of this workaround. Thanks!

**Comment by kimi-chen** [comment]
Here is another solution. Use fileloader in webpack, so you dont really need put under weird static folder anymore. For example, load images.
1. Under package.json, add
`  "electronWebpack": {
    "renderer": {
      "webpackConfig": "webpack.renderer.additions.js"
    }
  }`
2. Run 'Yarn add file-loader raw-loader'
3. Add a file called "webpack.renderer.additions.js" under your project root
`module.exports = function(config) {
   const fileRules = config.module.rules.filter(rule =>
    rule.test.toString().match(/\.(png|svg|jpg|gif|jpeg)$/)
  )

  fileRules.forEach(rule => {
    const cssLoader = rule.use.find(use => use.loader === 'file-loader')
    // this is the actual modification we make:
    cssLoader.options.modules = 'local'
  })

  return config
}`

**Comment by loopmode** [comment]
Interesting approach, and obviously it should work well!
However, I prefer to avoid relative paths with ../../. While modern editors and IDEs can correctly auto import and update import paths, it's fragile when refactoring folder structure of source files.

**Comment by loopmode** [comment]
And actually.. why is this issue I opened still open??? It has been long fixed - static folder works well in production by now!

**Comment by galactic-dust** [comment]
2021 still doesnt work properly lmao
