### ISSUE TITLE
Question: how to link CSS

### ISSUE THREAD

**Issue by facelesspanda** [electron-userland/electron-webpack#53]
Hi. I've read the doc through and I can't understand how to do this simple task:
I want to have a `<link rel='stylesheet'/>` in my `<head></head>` when the app loads.

I know you can extend the webpack configuration, but I've read that electron-webpack already includes a css loader. If so then where should I put the css file so that it's loaded and added? Maybe it's a simple configuration I have to put in the package.json, but the doc says absolutely nothing about this.

Electron-webpack is awesome for the whole webpack dev server thing, saves a lot of time, but I'd really like to know how to add css to my html.

**Comment by facelesspanda** [comment]
Okay I fixed it.
I forgot how webpack considered everything to be a js module before loading it.

So if you want to add `css` to your `html`, you need to `import 'style.css` in your `renderer/index.js`

This is not obvious, it should be addressed somewhere in the doc, it would prevent cases like this where an issue is created when none should be.

**Comment by loopmode** [comment]
Well I personally don't think it belongs into the electron-webpack docs.

Please keep in mind that this is not specific to `electron-webpack` at all. It's rather a webpack ecosystem thing, and actually it is obvious when you've worked with webpack and css-loader/style-loader etc. It's basically covered in the docs and tutorials for those libs.

**Comment by pieterdt** [comment]
I get your stance @loopmode on the other hand, people end up very quickly with electron-webpack when they endeavor on an electron journey. This often happens without webpack experience.

**Comment by MatthewRorke** [comment]
I think this issue should be reopened and addressed as it is an extremely common use-case that requires an understanding of webpack itself in order to use properly. In my opinion, the purpose of electron-webpack would be to mitigate the need for a deep understanding of webpack and to support styles and html out-of-the-box (as advertised). But this is not necessarily the case.

I'd love to know the correct way to handle implementing stylesheets without having to use a webpack config file with loaders.
