### ISSUE TITLE
remote.require('./lib/config') not working

### ISSUE THREAD

**Issue by icode** [electron-userland/electron-webpack#62]
```js
const {remote} = require('electron');
remote.require('./lib/config') // throw error
```

dev mode

**Comment by IGassmann** [comment]
`remote.require` seems to be referencing the bundled main process file `dist/main/main.js`.

That's also a problem for when you decide to name your main process' entry point as `index.js`. `remote.require('./index.js');` won't work. You'll have to use `remote.require('./main.js');`

A workaround for this issue is to export modules inside your main process' entry point like this:
`export const libConfig = require('./lib/config');`
Then you can import it as follow:
`const libConfig = remote.require("./main.js").libConfig;`
