### ISSUE TITLE
how to use custom index.html and or other non index.html

### ISSUE THREAD

**Issue by greggman** [electron-userland/electron-webpack#69]
Sorry this is probably a webpack-ish question but it seems like it might also be related to how electron-webpack is configured

I started with the electron-webpack-quick-start. My app actually opens 3 different windows each starting with a different html file. It's actually an existing app and I was trying to switch it to electron-webpack hoping it would solve some of my webpack issues.

I have my own `src/main/index.js`. It's running, it tries to open "/window1.html" using code like this adapted from what was in the original `src/main/index.js`

```
function createWindowUrl(url) {
  const prefix = isDevelopment
    ? `http://localhost:${process.env.ELECTRON_WEBPACK_WDS_PORT}`
    : `file://${__dirname}`;

  return `${prefix}/${url}`;
}

function createWindow(path) {
   ...
  window.loadURL(createWindowUrl(path));
   ...
}

app.on('ready', () => {
  createWindow('window1.html');
});

```

So I make a `src/renderer/window1.html` but of course as you've probably guessed get

     cannot GET /window1.html

So I move it to `static/window1.html`. Now it loads the html but this code inside window1.html does not work

    <script>require('js/window1.js');</script>

Nor this

    <script>require('./js/window1.js');</script>

`window1.js` exists in `src/renderer/js/window1.js`

Not sure what the correct path is supposed to be. And of course because it's static [the docs](https://webpack.electron.build/using-static-assets) don't seem to cover this case of computing the path since the path I want for `window1.js` is not relative to `__static` it's relative to wherever the built files exist.

What is the correct way to do this? Where do I put the HTML files? In static? If the HTML file references images, css etc, what's the correct path from within the HTML files? Relative paths? Some kind of templated path? What about any non-static things I want the html to render.

Ultimately I need to be able to do this

```
app.on('ready', () => {
  createWindow('window1.html');   // opens window1.html running src/renderer/js/window1.js
  createWindow('window2.html')   // opens window2.html running src/renderer/js/window2.js
  createWindow('window3.html');  // opens window3.html running src/renderer/js/window3.js
});
```

But I guess I'm kind of lost on how to do this. Sorry if these are totally noob webpack questions.

**Comment by loopmode** [comment]
No worries about the question being noob. In fact the underlying problem popped up a couple times recently, in different issues. Not sure if this can currently be done with electron-webpack. It seems, it was built under the premise that the HTML is just a wrapper the developer doesn't want to care about, and there is just one and it simply delivers a single webpack entry point. let's see what other devs have found so far

**Comment by IGassmann** [comment]
Is there any workaround for referencing electron-webpack's compiled styles and scripts on a custom index.html file?

**Comment by mdgilene** [comment]
Any update to this issue or possible workarounds?

**Comment by ivanvza** [comment]
Hi :)
I'm fairly new to electron-webpack however, I myself have this dilemma...

I have an older project that made use of [electron-navigation](https://github.com/simply-coded/electron-navigation) which had the following setup: 

main.js: 
`win.loadURL('file:///${__dirname}/app/main.html');`

app/main.html:
```
<script> 
      const enav = new (require('electron-navigation'))({
        showAddTabButton: true
    	});
      // create new tab, returns the webview element
      /*
      enav.newTab('https://web.something.com/');
</script>
```
And a new tab will be opened.

I'm a tad confused how I would go about in doing this with the current setup, as the renderer is pretty hard set to only .js (vuejs) files, or am I going to a rabbit hole?

Ultimately I would just like to follow the same principle in loading an HTML page to execute/render the tabs, unless there is an alternate method.

**Comment by loopmode** [comment]
From the `webpack` channel in the `electrin-builder` Slack workspace (starting at https://electron-builder.slack.com/archives/C76R7ARUH/p1516571742000014)

Gum-Joe [22:55 Uhr]
Hi
[22:56 Uhr]
Anyone here know how to setup a custom HTML page to load when the app is run (in dev mode)?
Gestern

----- Januar 22. -----

loopmode [07:31 Uhr]
@Gum-Joe similar questions were asked recently, and it seems that's not possible out of the box.
however...
...
2) since a while, we can specify custom webpack configs with `electron-webpack` and under the hood, `webpack-merge` is used with the smart strategy (https://github.com/survivejs/webpack-merge#smart-merging)
The docs there don't say how it merges plugins, only speaks about loaders. But maybe you can just define your own `html-webpack-plugin` definition with a `template` value in a custom config and it would be merged?

Haven't tried this out myself, but maybe you can look into 

Gum-Joe [17:06 Uhr]
Yes I did get it working

[17:06 Uhr]
It was simple:

[17:07 Uhr]
https://github.com/Gum-Joe/tara/blob/move-to-electron-webpack/webpack.config.dev.js see the pug in section. Just include the plug in and the default configuration is overriden

[17:07 Uhr]
```plugins: [
    new HtmlWebpackPlugin({
      title: "Tara",
      template: "src/html/index.html",
      hash: true
    })
  ]
```

[17:08 Uhr]
Some stuff can not be overridden, such as warnings (`stats: "minimal"` for example does nothing, warning still appear)

**Comment by Gum-Joe** [comment]
Note: I think this only works with one HTML, though presumably you should be able to use multiple ones as you can set different output paths. As the html files are next to the js in the build tree, it should be as simple as loading either `file://${__dirname}/name.html` or just webpack server://name.html

**Comment by Gum-Joe** [comment]
Just set filename to the file you want to output as and template as the input HTML to include (or ejs for that matter)

**Comment by fabiospampinato** [comment]
I've added a way of overriding the default HTML template in #261, this should greatly help in solving this issue.

For multi-windows apps I think you should do some routing, I've published this very simple router for solving the problem: https://www.npmjs.com/package/react-router-static, just add a `?route=***` parameter to the url you're set.

**Comment by loopmode** [comment]
Closing this issue for now. See last comment by @fabiospampinato which basically sums up your options.
