### ISSUE TITLE
How to pass command line switches onto the application?

### ISSUE THREAD

**Issue by Infiltrator** [electron-userland/electron-webpack#73]
I would like to run something similar to `yarn electron-webpack dev -- --switch-a --switch-b` and have electron-webpack pass the switches onto the actual application, but I have found nothing in the docs and fiddling with it has produced no results.

Alternatively, can I get electron-webpack to output to a directory where I can manually run `electron --switch-a --switch-b path/to/directory`?

**Comment by loopmode** [comment]
So you want to pass flags from the CLI to your own application, is that correct?
Assuming that is correct, you'll basically face two hurdles here: Passing flags to your app at development time is one thing, passing them at production is a different thing. I think both bring different difficulties. 
I never figured that out myself, but I found a workaround: Using environment variables.

In the simplest case, depending on the OS you're working on, you can simply set env variables just before launching whatever you want to launch:

Mac/Linux: `FOO=foo yarn dev`
Windows: `set FOO=foo&& yarn dev` 
(careful with the spaces there - no space between value and `&&` or you'll have the whitespace in you value)
With `cross-env`: `cross-env FOO=foo yarn dev` 
(Assumes you have `cross-env` installed globally!)

Then in your code, you access `process.env.FOO` and get your values.

Instead of using `cross-env` globally and directly from the CLI, I only install it locally in my project, then use additional scripts.
In development I have several scripts in package json:
```
"scripts": {
    ...
    "dist:build:rebreather": "cross-env JBM_SELECTED_GADGET=rebreather NODE_OPTIONS='--max-old-space-size=8192' electron-builder",
    ...
  },
```

For the production build, I generate "launcher scripts" that set env vars and then launch the app.
For example, for Windows, I create batch files that look like this:
```
set JBM_SELECTED_GADGET=goldengun
set JBM_LOG_LEVEL=debug
start gadget-archive.exe
exit
```

There are various tools and approaches for managing env vars, like `env-cmd` where you can have named env config files and then launch with a specific one. That file then sets several env values at once
I tried a couple and came back to `cross-env` as 1) it was the only one that was correctly setting all the crazy things I needed (like `NODE_OPTIONS='--max-old-space-size=8192'`), and 2) I couldn't mix-and-match the different tools, like using both `env-cmd` and `cross-env` was problematic.


So, I hope someone answers your question directly, and we all learn from it.
In any case, the workaround using env vars might be worth a shot. It may look a bit clumsy, but it's quite robust and flexible.
