### ISSUE TITLE
Is there a more straightforward-bare bones way to use electron and webpack together

### ISSUE THREAD

**Issue by ryzokuken** [electron-userland/electron-webpack#88]
Just wanted to confirm with the contributors if there were a simpler, albeit more bare-bones way to get electron running with webpack? It has become increasingly simpler to make frontend projects using the webpack, and honestly, if all this code is required to make it work, then nobody's better off making their own solutions.

I was especially wondering if I could just wrap all the required configuration into a single `webpack.config.js`, albeit in a very application-specific way.

**Comment by develar** [comment]
What problem do you have?

**Comment by ryzokuken** [comment]
I don't have a problem at all! But looking at the codebase and all the hard work you have put into the development of this project, it occurred to me that if this much work is required to get electron and webpack working together, then making a custom config is probably not feasible.

I was thinking of making a neutrino preset for electron and was wondering if there was a simpler way, that's it.

**Comment by develar** [comment]
No, no simple way.

In short:
1. HMR. Original webpack doesn't provide HMR for main process.
2. Simplified runner for both main and renderer processes. Original webpack designed for one process. But you need to compile and prepare both.
3. Presets — it is exactly what this tool does and why was born — detects what is required for your project and automatically configures webpack. No way to simplify this part of code.

I would say that now project is complete. All currently opened issues are not related to project itself and only reflects complexity of building and webpack. I mean — we can help users, but it requires a lot of effort. Like consultation. And it requires deep understanding of user project and so, time consuming. That's why project has 33 opened issues.

**Comment by develar** [comment]
> I was thinking of making a neutrino preset for electron

I suggest contribute to existing (for example, this project it is not to a new project, but result of electron-vue reworking (thanks to @SimulatedGREG)).

**Comment by develar** [comment]
> I was thinking of making a neutrino preset for electron

I suggest contribute to existing project and join forces (for example, this project it is not a new project, but result of electron-vue reworking (thanks to @SimulatedGREG)).

BTW, @SimulatedGREG when electron-view will be merged into this project officially :)?

**Comment by ryzokuken** [comment]
I agree. I have been using both of these projects lately and have been really satisfied with how well they work. I used `electron-vue` first and came across this one later when looking for a less opinionated alternative. I understand that it may not get any simpler than this to setup webpack for electron. Over the course of the new few days, I would try getting more and more familiar with the codebase, and perhaps I could be of some help to you guys after that.
