### ISSUE TITLE
Can't remove loaders

### ISSUE THREAD

**Issue by SrKomodo** [electron-userland/electron-webpack#92]
In my use case i would like to load svg files using `raw-loader` instead of the default `url-loader` shown here

```js
{
  test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
  use: {
    loader: 'url-loader',
    options: { limit: 10240, name: 'imgs/[name]--[folder].[ext]' }
  }
},
```

You would think that this could be fixed by creating a custom config, and then merging it with the default one like this

```js
// webpack.renderer.additions.js
module.exports = {
  module: {
    rules: [
      {
        test: /\.svg$/,
        use: 'raw-loader'
      }
    ]
  }
}
```

```json
// package.json
"electronWebpack": {
  "renderer": {
    "webpackConfig": "./webpack.renderer.additions.js"
  }
},
```

But you will see that this will not work, because you cant remove loaders in `webpack-merge`, and because webpack itself doesn't care if two loaders handle the same files

The only solution that i can think of would be to create a system to let you remove a loader, or at least change the `test` property of it

**Comment by loopmode** [comment]
Have you tried overridding `url-loader` in addition?

```
// webpack.renderer.additions.js
module.exports = {
  module: {
    rules: [
      {
        test: /\.svg$/,
        use: 'raw-loader'
      },
      {
        test: /\.(png|jpe?g|gif)(\?.*)?$/,
        use: {
          loader: 'url-loader',
          options: { limit: 10240, name: 'imgs/[name]--[folder].[ext]' }
        }
      },
    ]
  }
}
```

**Comment by SrKomodo** [comment]
@loopmode That doesn't work because `merge.smart` only combines loaders if they have the same `test` property, so there is no way to change the `test` property of the `url-loader`. The resulting loader array would look like this

```js
{
  test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
  use: [{
    loader: 'url-loader',
    options: { limit: 10240, name: 'imgs/[name]--[folder].[ext]' }
  }]
},
{
  test: /\.svg$/,
  use: 'raw-loader'
},
{
  test: /\.(png|jpe?g|gif)(\?.*)?$/,
  use: {
    loader: 'url-loader',
    options: { limit: 10240, name: 'imgs/[name]--[folder].[ext]' }
  }
}
```

Because webpack doesn't care if two loaders modify the same file, they will all modify the file in succession, and as you can imagine this results in incorrect output

I also tried to "break" the `url-loader` by adding invalid properties

```js
{
  test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
  use: 'invalid-loader'
},
{
  test: /\.svg$/,
  use: 'raw-loader'
},
{
  test: /\.(png|jpe?g|gif)(\?.*)?$/,
  use: {
    loader: 'url-loader',
    options: { limit: 10240, name: 'imgs/[name]--[folder].[ext]' }
  }
}
```

thinking that maybe it would not execute so that we can use our own loaders, but this just completely stopped webpack from running, so that isn't an option

**Comment by loopmode** [comment]
I see.
I just submitted a PR that might help:
https://github.com/electron-userland/electron-webpack/pull/93

It would allow you to export a function instead of an object in the custom webpack config, thereby bypassing `wenpack-merge` altogether.
You could then find the rule in question by comparing the value of `test` - note: you can compare regexes using their `toString()` function, e.g. `const a = /foo/g; const b = /foo/g; console.log(a.toString() === b.toString())`

My PR change is pretty naive and not even tested, but it should be good enough for the case. 
The biggest concern I see is that it's quite similar to https://webpack.electron.build/extending-as-a-library#mycustomwebpackrendererconfigjs, but still different. So, we have "yet another way of doing it", but for me, personally, that's not a bad thing.

Similarities: 
- possible to return full config instead of modifications
- possible to use async (or return a promise)
Differences:
- function receives current `config` object instead of `env`

Surely we could also pass `env` as a second argument. (Maybe we can even just access `process.env` at this time? Not sure)

Let's see what @develar thinks about this.

**Comment by Gvozd** [comment]
@SrKomodo replace `invalid-loader` to `do-nothing-loader`(it's real loader in npm), and this workaround worked!

**Comment by GitHubJasper** [comment]
@Gvozd I tried that workaround but it still loads the svg with `url-loader`.
How did you get it to work or does it no longer work?

**Comment by hidden4003** [comment]
So how do I actually solve this? I need to use svgr/webpack to convert my svg into components but I can't override the rule.

**Comment by mjashanks** [comment]
I just made a PR  which i'm pretty sure will solve this : #291 . You will be able to override any rules, using thin full webpack-merge api.

Would love to get this merged in asap.

**Comment by loopmode** [comment]
@SrKomodo Version 2.7.0 was released and it allows your config to export a function instead of an object. You may manipulate the config in any way you like in this function - e.g. remove, change or add loaders - and then return the final config object.

The docs have not been published yet, but will be soon. See the [commit itself](https://github.com/electron-userland/electron-webpack/commit/bb96fce0224f17153159ddd44457724ce7b65540#diff-16f8ab5d68543dc231b56ab510ef59d2R68) until then, or just take this short documentation:

1) Configure electron-webpack to use custom webpack config, e.g. in `package.json`:
```
{
  "electronWebpack": {
    "renderer": {
      "webpackConfig": "webpack.renderer.js"
    }
  }
}
```

2) Provide a function instead of an object in that configuration file:
```
// webpack.renderer.js
module.exports = function(config) {
    // console.log(JSON.stringify(config, null, 4));

    // find the rule
    const imageRule = config.module.rules.find(rule =>{
        return rule.test.toString() === '/\.(png|jpe?g|gif|svg)(\?.*)?$/'
    });

    // override its test
    imageRule.test = /\.(png|jpe?g|gif)(\?.*)?$/

    // add your extra rule
    config.modules.rules.push({ test: /\.svg$/, use: 'raw-loader' })

    // finally return the modified config
    return config;
}
```

3) If you already have a setup relying on webpack merge smart, you can still combine it:
```
// webpack.renderer.js
const merge = require('webpack-merge');
module.exports = function(config) {
    config = merge.smart(config, {
        // ... whatever you have
    });
    // plus all the stuff from the snippet above as needed
}
```

Please note that I haven't actually tested the snippets above, but you get the idea. 

Since 2.7.0 allows you to remove loaders, I'm closing this issue.
Please reopen if needed.

**Comment by SrKomodo** [comment]
After more than a year, this issue has finally been fixed. Thank you so much

**Comment by loopmode** [comment]
Yeah.. Basically it's just @develar - who gave us this awesome piece of work, for free - and a bunch of dudes like myself, doing their daily job.

I haven't worked with electron myself for like 2 years by now. But whenever life and wife allow it.. I spend some time here.. but of course it's not enough

Contributors are very welcome tho! :)
